language: ruby
cache: bundler
deploy:
- provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  fqdn: teambathracingelectric.com
  local-dir: _site
  target-branch: master 
  on:
    branch: source