url: https://teambathracingelectric.com

# Site settings
title: Team Bath Racing Electric
email: teambathracingelectric@gmail.com
description: >
  Team Bath Racing Electric (TBRe) is an engineering team run by students at
  the University of Bath. The team has a range of engineering students working
  together to design and build an electric high-performance vehicle for the
  Formula Student competition. We want to inspire students from all engineering
  disciplines to collaborate on a challenging and motivating project.

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social-icons:
  - title: facebook
    url: https://www.facebook.com/TeamBathRacingElectric/
  - title: instagram
    url: https://www.instagram.com/teambathracingelectric/
  - title: twitter
    url: https://twitter.com/TeamBathRacingE
  - title: linkedin
    url: https://www.linkedin.com/company/team-bath-racing-electric/
  - title: youtube
    url: https://www.youtube.com/channel/UCn7s-HVkYWgW37Ur_5DrgXg

author: James Raikes
# Postal address (add as many lines as necessary)
address:
  - line: Team Bath Racing Electric
  - line: Dept of Electronic & Electrical Engineering
  - line: University of Bath
  - line: Bath
  - line: BA2 7AY
  - line: United Kingdom

# Build settings
# permalink: pretty

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Rakefile
  - README.md
  - LICENSE
  - .jekyll-cache/
  # Remove the below entries to add them back to the site
  - _posts/
  - mail/
  - _layouts/feed.xml
  - feed.xml

# gh-pages emulation
# safe: true
# repository: raikesy/TBRe-website

# Google Analytics
google_analytics: UA-115200564-1

# These are used by the jekyll-seo-tags plugin for SEO
logo: img/tbre-sq-logo.jpg

twitter:
  username: TeamBathRacingE

facebook:
  app_id: 1953013801682223
  publisher: 1480074792275446

social:
  links:
    - https://www.facebook.com/TeamBathRacingElectric/
    - https://www.instagram.com/teambathracingelectric/
    - https://twitter.com/TeamBathRacingE
    - https://www.linkedin.com/company/team-bath-racing-electric/
    - https://www.youtube.com/channel/UCn7s-HVkYWgW37Ur_5DrgXg

webmaster_verifications:
  google: R44jnjlcvr3YfeIDfyj9K2DTJU2fnuoXynMT0UzkDpQ
  bing: 7F60D5F5E79FFCB585A069021A41C6BA

lang: en-GB

compress_html:
  ignore:
    envs: [development] # Not ignoring dev currently

# Polyglot
languages: ['en-GB', 'zh-CN']
default_lang: 'en-GB'
exclude_from_localization: ['img', 'js']
parallel_localization: true

# Jekyll Assets Plugin
# assets:
#   autoprefixer: # Not currently working
#     # browsers:
#     #   - "IE 6"
#     #   - "Chrome 9"
#     #   - "Firefox 14"
#     browsers: ["IE 6", "Chrome 9", "Firefox 14"]
#   caching:
#     enabled: false