url: http://127.0.0.1:4000/
baseurl: /

# Site settings
title: Team Bath Racing Electric
email: info@teambathracingelectric.com
description: >
               "Team Bath Racing Electric (TBRe) is an engineering team run by students at the University of Bath.
               The team has a range of engineering students working together to design and build an electric high-performance
               vehicle for the Formula Student competition. We want to inspire students from all engineering disciplines to
               collaborate on a challenging and motivating project."

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/TeamBathRacingElectric/
  - title: twitter
    url: https://twitter.com/TeamBathRacingE
  - title: linkedin
    url: https://www.linkedin.com/company/9378203

# Postal address (add as many lines as necessary)
address:
  - line: University of Bath, Claverton Down
  - line: Bath, BA2 7AY

# Build settings
markdown: kramdown
permalink: pretty
